---
AWSTemplateFormatVersion: '2010-09-09'
Parameters:
  GroupName:
    Type: String
    Default: testing-users-group
    Description: Preferred name for the group
Resources:
  MFAPolicy:
    Type: AWS::IAM::Group
    Properties:
      GroupName: !Ref 'GroupName'